### PR TITLE
response text returned a newline

### PR DESCRIPTION
**Pull request by brandesdavid**
Please check the function and test if the response text still returns a \n in the console

### CODE REVIEW

**Review by FinnRainer — CHANGES_REQUESTED** [review]
\n is still present

**Comment by brandesdavid** [comment]
> \n is still present in the direction id and station id in Postico

@FinnRainer how did you test the newline? please clarify.

i tested using

```python

class Message:
    def __init__(self, text):
        self.text = text

message = Message('S7 Alexanderplatz Richtung Hauptbahnhof')
process_new_message(1, message, datetime.datetime.now(), {})

```` 

and did not get any newlines in database ....

**Review by johan-t — CHANGES_REQUESTED** [review]
If you test with the bot running there will still be newlines when the data is added to postico so maybe a newline is added also somewhere else.

**Review by johan-t — APPROVED** [review]
Never mind it works

**Comment by brandesdavid** [comment]
😃

**Pull request merged**
